from typing import Protocol, Any


class BillingProviderAdapter(Protocol):
    def create_customer(self, organization: Any): ...
    def create_checkout_session(self, organization_id: str, plan_id: str): ...
    def get_subscription(self, provider_subscription_id: str): ...
    def cancel_subscription(self, provider_subscription_id: str): ...
    def create_billing_portal_session(self, organization_id: str): ...
    def handle_webhook(self, payload: bytes, signature: str | None): ...
