"""phase10_models

Revision ID: 7054888e2a84
Revises: 20260524_0003
Create Date: 2026-05-28 04:32:38.025696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7054888e2a84'
down_revision: Union[str, None] = '20260524_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_refresh_tokens_token_hash'), ['token_hash'])
        batch_op.create_foreign_key(batch_op.f('fk_refresh_tokens_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('scheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('schedule_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('cron', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=False))
        batch_op.alter_column('interval_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_scheduler_jobs_name'), ['name'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('display_name')
        batch_op.drop_column('email')

    with op.batch_alter_table('scheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduler_jobs_name'))
        batch_op.alter_column('interval_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('payload')
        batch_op.drop_column('cron')
        batch_op.drop_column('enabled')
        batch_op.drop_column('schedule_type')
        batch_op.drop_column('job_type')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_refresh_tokens_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_refresh_tokens_token_hash'), type_='unique')

    # ### end Alembic commands ###
